package com.github.se.orator.model.symblAi

enum class SpeakingError {
  NO_ERROR,
  CREDENTIALS_ERROR,
  ACCESS_TOKEN_ERROR,
  HTTP_REQUEST_ERROR,
  JOB_PROCESSING_ERROR,
  MISSING_CONV_ID_ERROR,
  JSON_PARSING_ERROR,
  NO_MESSAGES_FOUND_ERROR
}
